stages:
  - build
  - deploy

build:
  image: elixir:latest
  stage: build
  script:
    - mix deps.get
    - MIX_ENV=prod mix release
  artifacts:
    paths:
      - _build/prod/rel/ptah_agent
    untracked: false
    when: on_success
    access: all
    expire_in: "15 mins"

deploy-job:
  image:
    name: d3fk/s3cmd
    entrypoint: [""]
  stage: deploy
  before_script:
    - apk add tar xz
  script:
    - tar -cvJf ptah_agent.tar.xz -C _build/prod/rel ptah_agent
    - s3cmd put --acl-public ptah_agent.tar.xz s3://$S3_BUCKET/ptah/ptah_agent_latest_linux_x86_64.tar.xz
      --access_key=$S3_ACCESS_KEY
      --secret_key=$S3_SECRET_KEY
      --host-bucket="%(bucket)s.nyc3.digitaloceanspaces.com"
