on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_RELEASE_PLEASE_TOKEN }}
          release-type: elixir
