on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'
      - run: mix deps.get
      # TODO: add `mix test` when tests will be written. :)
      - run: MIX_ENV=prod mix release
      - run: tar -cvJf ptah_agent.tar.xz -C _build/prod/rel ptah_agent
      - uses: actions/upload-artifact@v4
        with:
          name: ptah_agent
          path: ptah_agent.tar.xz

  release-please:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_RELEASE_PLEASE_TOKEN }}
          release-type: elixir
      - uses: actions/download-artifact@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: ptah_agent
      - run: gh release upload ${{ steps.release.outputs.tag_name }} ptah_agent.tar.xz
        if: ${{ steps.release.outputs.release_created }}
